apiVersion: v1
kind: Pod
metadata:
  name: captcha-api
  labels:
    app.kubernetes.io/name: captcha-api
spec:
  containers:
  - name: myclickhouse 
    image: mrmtonio/captcha-api
    env:
    - name: CLICKHOUSE_PORT
      value: "9000"
    - name: KAFKA_TOPIC_NAME
      value: captcha
    - name: KAFKA_BOOTSTRAP_SERVER
      value: "kafka.confluent.svc.cluster.local:9071"
    - name: CLICKHOUSE_HOST
      value: "myclickhouse.clickhouse.svc.cluster.local"
    ports:
      - containerPort: 8000
        name: api
---
apiVersion: v1
kind: Service
metadata:
  name: captcha-api
spec:
  selector:
    app.kubernetes.io/name: captcha-api
  ports:
  - name: api-svc
    protocol: TCP
    port: 8000
    targetPort: api
