apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: imachines-tt
  region: us-east-1

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        albIngress: true

