apiVersion: v1
kind: Pod
metadata:
  name: myclickhouse
  labels:
    app.kubernetes.io/name: clickhouse
spec:
  containers:
  - name: myclickhouse 
    image: clickhouse/clickhouse-server
    ports:
      - containerPort: 8123
        name: http-interface
      - containerPort: 9000
        name: native-client
---
apiVersion: v1
kind: Service
metadata:
  name: myclickhouse
spec:
  selector:
    app.kubernetes.io/name: clickhouse
  ports:
  - name: http-interface-svc
    protocol: TCP
    port: 8123
    targetPort: http-interface
  - name: native-client-svc
    protocol: TCP
    port: 9000
    targetPort: native-client
